# Generated by Django 2.1.7 on 2019-12-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('noveltype', models.CharField(max_length=30)),
                ('novelindex', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': '小说',
            },
        ),
    ]
