# Generated by Django 2.1.7 on 2019-12-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='novel',
            table='novel_info',
        ),
    ]
